### ISSUE TITLE
E-3 Create basic GUI for the GCS

### ISSUE THREAD

**Issue by John15321** [PWr-Aerospace/ground-control-station#1]
### Description

Create a basic GUI for the GCS based on this sketch:
![image](https://user-images.githubusercontent.com/56229312/226219311-6ce4417c-a006-47b2-a666-595859cad133.png)

So that all the specified functionalities in the Mission Guide can be implemented.

**Comment by John15321** [comment]
The current state of the GUI being done in React:
![image](https://user-images.githubusercontent.com/56229312/226219391-b9ecc64f-e1c1-4db8-b9ee-64cfef4d190c.png)

**Comment by John15321** [comment]
Current progress:
The draft of the UI is complete with all of its basic functionalities like live drawing of data from the backend or tabs with individual plots:

![image](https://user-images.githubusercontent.com/56229312/231136178-4d3f7adf-a9f8-4a7a-b525-f2b31c78cc71.png)

**Comment by jkaszowski** [comment]
The only part of cansat that contains FSM is Payload. The Container has only camera, power supply and a switch. Therefore, the Container should not have its software state displayed - it does not exist.

**Comment by jkaszowski** [comment]
What is "pointing error" ?

**Comment by jkaszowski** [comment]
What is the purpose of button "start" ?

**Comment by jkaszowski** [comment]
Also, please leave one button to "stop and save csv"
